amazon.dynamodb.endpoint:
aws.access.key.id:
aws.secret.access.key:

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1
