amazon.dynamodb.endpoint: http://localhost:8000/
aws.access.key.id: dummy
aws.secret.access.key: dummy

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: create-only
        gsiProjectionType: ALL
        readCapacity: 10
        writeCapacity: 1




