package com.example.billspliter.groupmanagement

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.example.billspliter.usermanagement.Spend
import com.example.billspliter.usermanagement.UserDAO

@DynamoDBTable(tableName = "groups")
data class GroupDAO(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String,
        @DynamoDBAttribute
        var name: String,
        @DynamoDBAttribute
        var members: Map<UserDAO, List<Spend>>,
        @DynamoDBAttribute
        var summary: Map<UserDAO, Double>
)