package com.example.billspliter.groupmanagement

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.example.billspliter.usermanagement.Spend
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import java.sql.Date
import java.sql.Timestamp

@DynamoDBTable(tableName = "groups")
data class GroupDAO(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,
        @DynamoDBAttribute
        var name: String = "",
        @DynamoDBAttribute
        var imageURL: String = "",
        @DynamoDBTypeConverted(converter = UserDAOMapConverter::class)
        var members: MutableList<MemberHistory> = mutableListOf()

//        @DynamoDBTypeConverted(converter = UserDAOMapConverter::class)
//        var summary: Map<UserDAO, Double> = mapOf()
)

data class MemberHistory(
        var userId: String = "",
        var spends: MutableList<SpendDAO> = mutableListOf()
)

data class SpendDAO(
        val title: String,
        val date: Long,
        val value: Double,
        val imageURL: String,
        val userName: String,
        val concerns: List<String>
)


class UserDAOMapConverter : DynamoDBTypeConverter<String, MutableList<MemberHistory>> {

    private val objectMapper = jacksonObjectMapper()

    override fun unconvert(`object`: String): MutableList<MemberHistory> {
        return objectMapper.readValue(`object`)
    }

    override fun convert(`object`: MutableList<MemberHistory>): String = objectMapper.writeValueAsString(`object`)
}