package com.example.billspliter.usermanagement

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.amazonaws.util.json.Jackson
import com.example.billspliter.groupmanagement.GroupDAO
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.KeyDeserializer
import org.springframework.security.core.userdetails.UserDetails

@DynamoDBTable(tableName = "users")
data class UserDAO(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,
        @DynamoDBAttribute
        var name: String = "",
        @DynamoDBAttribute
        var password: String = "",
        @DynamoDBAttribute
        var imageURL: String = "",
        @DynamoDBAttribute
        var groups: MutableList<GroupDAO> = mutableListOf(),
        @DynamoDBAttribute
        var friends: MutableList<UserDAO> = mutableListOf()
)